version: "2.2"

services:
  compose-nginx:
    image: nginx
    ports: 
     - 9000:80
    volumes:
     - ./index.html:/usr/share/nginx/html/index.html

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: samyog
    ports:
     - 3306:3306
    volumes:
     - ./my-data:/var/lib/mysql
     phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: samyog
